<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Log in to Facebook_u_0_4_sG</name>
   <tag></tag>
   <elementGuidId>72332e38-89a5-44d9-a68b-581b69bf788a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='u_0_4_sG']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#u_0_4_sG</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9512b549-3e51-4fe2-907d-fee02d1448b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_9lsb _9ls8</value>
      <webElementGuid>9cc01252-4db4-404c-8a95-0356e0603fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_0_4_sG</value>
      <webElementGuid>152d8c50-3be3-441e-b362-cb29f6e04ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_4_sG&quot;)</value>
      <webElementGuid>f84045f6-c2a7-42fe-aca6-9211e55cac34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='u_0_4_sG']</value>
      <webElementGuid>36b46143-f8fa-42f5-8d53-ba54c5e85a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u_0_3_jA']/a/div/div</value>
      <webElementGuid>6778a610-2b84-4028-8f0a-d0241b9ab6f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div</value>
      <webElementGuid>0d068bd9-7ed6-48e2-a703-4473c26fe722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'u_0_4_sG']</value>
      <webElementGuid>eac1184c-6d89-41bf-91f9-9a6a5f63cc2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
