<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Log in to Facebook_u_0_4_Kl</name>
   <tag></tag>
   <elementGuidId>579b218a-c075-48ef-b5a5-c6c3bc2ad074</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='u_0_4_Kl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#u_0_4_Kl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>af9c852a-8cf2-49ba-85cf-3724c8dd4a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_9lsb _9ls9</value>
      <webElementGuid>4b38729f-9c64-4335-9254-8aa85d06d2d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_0_4_Kl</value>
      <webElementGuid>9dc34e7a-758c-4fca-83d3-c3c10ec7ff0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_4_Kl&quot;)</value>
      <webElementGuid>70395880-f368-4d46-9696-7adea61e5a9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='u_0_4_Kl']</value>
      <webElementGuid>423ed298-1a2f-480a-9e80-201f5d7a1713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u_0_3_lg']/a/div/div</value>
      <webElementGuid>560d0e06-03c1-4119-aa56-e761cc0c2e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div</value>
      <webElementGuid>fef12169-c971-4f5c-8b82-fd30a77944ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'u_0_4_Kl']</value>
      <webElementGuid>141e6536-9791-40bb-8c32-d2ac63420128</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
