<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Log in to Facebook_u_0_4_do</name>
   <tag></tag>
   <elementGuidId>4bc11396-9a50-4b12-a0f5-61d46424f402</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='u_0_4_do']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#u_0_4_do</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b275568e-ecc9-4762-a05a-08df2b1d452e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_9lsb _9ls8</value>
      <webElementGuid>7e772b69-d1f1-4474-b6c9-058cadcf4aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_0_4_do</value>
      <webElementGuid>a10b72bc-4db0-4693-acc6-1955c519480a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_4_do&quot;)</value>
      <webElementGuid>00d26112-c449-4ceb-9961-113009a3947f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='u_0_4_do']</value>
      <webElementGuid>ca2a4252-3fa0-474a-8f37-1e41813ed2b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u_0_3_jU']/a/div/div</value>
      <webElementGuid>70063948-6e4b-4ba1-876c-aea59763dcec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div</value>
      <webElementGuid>92f3a30f-3d44-4d04-bb86-7ae6e66e19f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'u_0_4_do']</value>
      <webElementGuid>c228e9dd-9ed1-4e4e-874c-8c8cb82bade5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
