<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Log in with password</name>
   <tag></tag>
   <elementGuidId>b7798d58-01a6-4a0f-84c4-6f365afa083e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='u_0_1_Dk']/div/div[3]/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a._aklt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>07ab34ea-38ea-4c22-ae28-3169bb2b9066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_aklt</value>
      <webElementGuid>949f50db-e993-46eb-adb4-3df69f1798c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/login/web/?cuid=AYilnK6LIMuSqKaq2JMyndxxxQ-j7ydM8QhZVBva9sQ2cNIXNli6aB7v4-Q4OopgDCxfM1f26OMSuD5b7eoCPp2_d-apaYcml0iehzfK2wwamP8AFqxlCvyj5RDowwz5V40Xe0KEmvLZ0ndx1Rce1iPEO7pkzlh9P_8ZwAiMoepaCHm5rfyfcqJdOp5qs8PmPEBLpp31ByUbBohsSgzMqnTtkie5ZmpjAzpfB8KNJEXiO7Ev94iZEyo1gePJI-pxic4EBcHV-kFR__02hIhph9x1&amp;email=drsbagas%40rocketmail.com&amp;is_from_lara=1</value>
      <webElementGuid>5a0135c0-e932-422d-b146-c180ccaa14bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log in with password</value>
      <webElementGuid>0b4446d2-1a6d-4444-a0ef-a1646e79c9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_1_Dk&quot;)/div[@class=&quot;mtl mbm ptm uiInterstitial _aklr uiInterstitialLarge uiBoxWhite&quot;]/div[@class=&quot;uiInterstitialBar _amyj uiBoxGray topborder&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;pts&quot;]/a[@class=&quot;_aklt&quot;]</value>
      <webElementGuid>fd3fcac0-d066-4b51-94c7-04858487b25a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='u_0_1_Dk']/div/div[3]/div/div[2]/a</value>
      <webElementGuid>924eb501-e385-43ef-9dd2-e8dc8cc23236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Log in with password')]</value>
      <webElementGuid>3687e77b-8932-4b42-aacb-8b57e6373657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/following::a[1]</value>
      <webElementGuid>fcc8942e-fba0-4f27-b21a-a3c499ba6475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try another way'])[1]/following::a[1]</value>
      <webElementGuid>a4b47775-1e71-4464-910c-3e166925be1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English (UK)'])[1]/preceding::a[1]</value>
      <webElementGuid>03e68815-e91f-4616-a918-94286e817bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bahasa Indonesia'])[1]/preceding::a[1]</value>
      <webElementGuid>bc84364d-9ac3-4657-941d-503c70422ab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Log in with password']/parent::*</value>
      <webElementGuid>e93443b0-ed33-42b0-9b34-b675f089fced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/login/web/?cuid=AYilnK6LIMuSqKaq2JMyndxxxQ-j7ydM8QhZVBva9sQ2cNIXNli6aB7v4-Q4OopgDCxfM1f26OMSuD5b7eoCPp2_d-apaYcml0iehzfK2wwamP8AFqxlCvyj5RDowwz5V40Xe0KEmvLZ0ndx1Rce1iPEO7pkzlh9P_8ZwAiMoepaCHm5rfyfcqJdOp5qs8PmPEBLpp31ByUbBohsSgzMqnTtkie5ZmpjAzpfB8KNJEXiO7Ev94iZEyo1gePJI-pxic4EBcHV-kFR__02hIhph9x1&amp;email=drsbagas%40rocketmail.com&amp;is_from_lara=1')]</value>
      <webElementGuid>70db0d16-694f-4949-8050-b7c1135f4b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>10a8229e-e4ae-43ea-8836-21bc36fc808a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/login/web/?cuid=AYilnK6LIMuSqKaq2JMyndxxxQ-j7ydM8QhZVBva9sQ2cNIXNli6aB7v4-Q4OopgDCxfM1f26OMSuD5b7eoCPp2_d-apaYcml0iehzfK2wwamP8AFqxlCvyj5RDowwz5V40Xe0KEmvLZ0ndx1Rce1iPEO7pkzlh9P_8ZwAiMoepaCHm5rfyfcqJdOp5qs8PmPEBLpp31ByUbBohsSgzMqnTtkie5ZmpjAzpfB8KNJEXiO7Ev94iZEyo1gePJI-pxic4EBcHV-kFR__02hIhph9x1&amp;email=drsbagas%40rocketmail.com&amp;is_from_lara=1' and (text() = 'Log in with password' or . = 'Log in with password')]</value>
      <webElementGuid>08bb4f84-d222-4530-951c-643d75eec109</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
